server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: file:/home/artur/repos/spring-cloud-config-server/config
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
